version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'customer_management'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    volumes:
      - 'mysql-data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      retries: 3
      timeout: 5s

  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '4001:4001'
    depends_on:
      - app

volumes:
  mysql-data:
